"""The no-repaint theorem for liquidity sweeps, class included.

A sweep is a fact about the candle it confirmed on: the level, the side, how
deep, and -- §4.4 -- whether the level was INTERNAL or EXTERNAL liquidity at
that moment. Everything after it is built on that record. §4.7's stop hunt
exists only for an EXTERNAL sweep, maturation reads the class back out of the
SWEPT evidence, and confluence's A1 archetype asks for the stop hunt.

So a sweep the replay published on a shorter window must be published,
identically, on a longer one -- and so must every fact that matured from it.
Before s5-v11 that failed: the sweep copied its class off the pool row, and the
row carries the class the window's *newest* extremes give it. Measured on 40
generated series, 39 of 1,619 sweeps changed class between a prefix run and
the full run, and 27 reclaim and displaced facts with them.

**No exceptions since s5-v13.** Two mechanisms used to be excluded here by
name, parked by the owner on 2026-09-13: (b) §4.2's dedup applied with the
newest candle's epsilon, so a level that was its own pool on the shorter window
could be absorbed by a neighbour on the longer one; and (c) a swing that joined
an equal-level cluster later being suppressed in favour of the cluster pool.
Both took the prefix's pool, and its sweep, out of the full run. The owner's
2026-09-14 ruling brought them into the fix -- the pool map is decided by
candle order alone -- so every sweep and matured fact must now stand.
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any

import pytest
from hypothesis import HealthCheck, event, given, settings
from hypothesis import strategies as st
from tests.golden.harness import runner
from tests.golden.harness.canonical import canonicalise
from tests.golden.harness.dataset import GoldenDataset
from tests.support.strategies import walking_candle_series

pytestmark = pytest.mark.property

_WARM = 300
_MAX_SERIES = 380

_MATURED = frozenset(
    {
        "LIQUIDITY_STOP_HUNT",
        "LIQUIDITY_STOP_HUNT_FAILED",
        "LIQUIDITY_SWEEP_RECLAIMED",
        "LIQUIDITY_SWEEP_DISPLACED",
    }
)


def _dataset(candles: list) -> GoldenDataset:
    return GoldenDataset(
        dataset_id="property-liquidity",
        engine="liquidity",
        sls_sections=("4.4",),
        sls_rules=("property",),
        description="generated",
        labelling_rationale="generated by a property test",
        labelled_by="hypothesis",
        labelled_at="generated",
        algo_version="property",
        symbol=candles[0].symbol,
        timeframe=candles[0].timeframe,
        candles=tuple(candles),
        expected={},
        path=Path("generated.json"),
    )


def _run(candles: list) -> dict[str, Any]:
    return canonicalise(asyncio.run(runner._run_liquidity(_dataset(candles))))


def _key(item: dict[str, Any]) -> str:
    return json.dumps(item, sort_keys=True)


@settings(
    max_examples=25,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.data_too_large],
)
@given(
    series=walking_candle_series(min_size=_WARM + 20, max_size=_MAX_SERIES),
    data=st.data(),
)
def test_a_published_sweep_and_its_class_are_never_rewritten(
    series: list,
    data: st.DataObject,
) -> None:
    """§4.4 and §4.6 at the replay: every sweep a prefix published, with its
    class, and every fact matured from it, stands in the full run."""

    split = data.draw(st.integers(min_value=_WARM, max_value=len(series) - 1), label="prefix")

    early = _run(series[:split])
    later = _run(series)

    later_exact = {_key(item) for item in later["events"]}

    for item in early["events"]:
        if item["event_type"] != "LIQUIDITY_SWEEP" and item["event_type"] not in _MATURED:
            continue

        event(f"prefix published {item['event_type']}")

        if item["payload"].get("liquidity_class") == "EXTERNAL":
            event("prefix published an EXTERNAL fact")

        assert _key(item) in later_exact, (
            f"{item['event_type']} at {item['event_at']} on {split} candles was revoked or "
            f"rewritten once the series grew to {len(series)}: {item['payload']}"
        )
