"""§3.6's MSS invalidation, reached on purpose.

*"Within 10 candles of an MSS, a close back beyond the pre-MSS extreme demotes
the new trend to RANGING and marks the MSS low_quality: true (fact
preserved)."*

`test_no_repaint_replays.py` holds every structure-shift event a prefix
publishes to the full run, but on `walking_candle_series` an invalidation
appears in about one series in twenty, so its 25 examples usually carried none
and `STRUCTURE_MSS_INVALIDATED` had no coverage at all. `mss_then_reclaim_series`
builds the MSS deliberately and draws whether, and when, price takes it back.

Two questions, both asked of the real `StructureShiftReplayService` through the
golden harness:

1. Does the invalidation happen exactly when §3.6 says -- a reclaim on candles
   1 to 10 after the MSS, never on 11 or later, never without one -- and does
   it record how many candles it took?
2. Once a prefix has published it, does the whole series publish it
   identically? An invalidation is a fact appended about an MSS; a longer
   window may add facts, never revoke or rewrite this one.
"""

from __future__ import annotations

import asyncio
from pathlib import Path
from typing import Any

import pytest
from hypothesis import HealthCheck, event, given, settings
from hypothesis import strategies as st
from tests.golden.harness import runner
from tests.golden.harness.canonical import canonicalise
from tests.golden.harness.dataset import GoldenDataset
from tests.support.strategies import mss_then_reclaim_series

pytestmark = pytest.mark.property

_INVALIDATION_WINDOW = 10
_INVALIDATED = "STRUCTURE_MSS_INVALIDATED_"

_SETTINGS = settings(
    max_examples=40,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.data_too_large],
)


def _events(candles: list) -> list[dict[str, Any]]:
    dataset = GoldenDataset(
        dataset_id="property-mss-invalidation",
        engine="structure_shift",
        sls_sections=("3.6",),
        sls_rules=("property",),
        description="generated",
        labelling_rationale="generated by a property test",
        labelled_by="hypothesis",
        labelled_at="generated",
        algo_version="property",
        symbol=candles[0].symbol,
        timeframe=candles[0].timeframe,
        candles=tuple(candles),
        expected={},
        path=Path("generated.json"),
    )

    return [
        canonicalise(item) for item in asyncio.run(runner._run_structure_shift(dataset))["events"]
    ]


@_SETTINGS
@given(case=mss_then_reclaim_series())
def test_an_mss_is_invalidated_exactly_when_price_reclaims_within_ten_candles(
    case: tuple[list, int | None],
) -> None:
    """§3.6's rule, both ways, with the count it must record."""

    _assert_the_ten_candle_rule(*case)


@pytest.mark.parametrize("edge", [1, 10, 11])
@settings(
    max_examples=5,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.data_too_large],
)
@given(data=st.data())
def test_the_window_edges_are_exact(edge: int, data: st.DataObject) -> None:
    """The three delays where a rule wrong by one candle parts from §3.6.

    Candle 1 is the first that may invalidate, candle 10 the last, candle 11
    the first that may not. Drawn at random they turn up too rarely to rely
    on -- a battery caught "window of eleven" in only two runs of three -- so
    each is pinned here, and the rest of the series is still drawn.
    """

    candles, reclaim_delay = data.draw(
        mss_then_reclaim_series(reclaim_delays=st.just(edge)), label="series"
    )

    _assert_the_ten_candle_rule(candles, reclaim_delay)


def _assert_the_ten_candle_rule(candles: list, reclaim_delay: int | None) -> None:
    events = _events(candles)

    mss = [item for item in events if item["event_type"] == "MSS_DOWN"]
    invalidations = [item for item in events if item["event_type"].startswith(_INVALIDATED)]

    # The premise, asserted rather than assumed: without the MSS there is
    # nothing to invalidate and the rule below would pass by absence.
    assert len(mss) == 1, f"the series was built to confirm one MSS_DOWN, got {len(mss)}"

    expected = reclaim_delay is not None and reclaim_delay <= _INVALIDATION_WINDOW

    if reclaim_delay is None:
        event("price never came back")
    elif expected:
        event("reclaimed inside the window")
    else:
        event("reclaimed after the window")

    # The delays where a rule wrong by one candle differs from the right one.
    if reclaim_delay in (1, 10, 11):
        event(f"reclaimed on an edge of the window: candle {reclaim_delay}")

    if not expected:
        assert not invalidations, (
            f"reclaim delay {reclaim_delay}: §3.6 allows no invalidation, the engine "
            f"published {[item['payload'] for item in invalidations]}"
        )
        return

    assert len(invalidations) == 1, (
        f"reclaim {reclaim_delay} candles after the MSS: §3.6 requires one invalidation, "
        f"the engine published {len(invalidations)}"
    )

    payload = invalidations[0]["payload"]

    assert payload["candles_since_confirmation"] == reclaim_delay
    assert payload["low_quality"] is True


@_SETTINGS
@given(case=mss_then_reclaim_series(), data=st.data())
def test_a_published_invalidation_is_never_revoked_or_rewritten(
    case: tuple[list, int | None],
    data: st.DataObject,
) -> None:
    """The no-repaint half: prefix events are facts the full run must keep.

    Half the splits end the prefix on the candle straight after the
    invalidation -- the moment the fact first exists -- because a split drawn
    anywhere lands before it more often than not. The target is read from the
    full run's own event, which is fair: a replay that published it early or
    late would not be caught by aiming at the wrong candle, only by the
    containment below failing.
    """

    candles, _ = case
    later = _events(candles)
    later_exact = {repr(sorted(item.items())) for item in later}

    invalidated_at = [
        index
        for index, candle in enumerate(candles)
        for item in later
        if item["event_type"].startswith(_INVALIDATED)
        and item["event_at"] == canonicalise(candle.open_time)
    ]

    if invalidated_at and data.draw(st.booleans(), label="aim at the invalidation"):
        split = invalidated_at[0] + 1
    else:
        split = data.draw(st.integers(min_value=300, max_value=len(candles) - 1), label="prefix")

    early = _events(candles[:split])

    for item in early:
        if item["event_type"].startswith(_INVALIDATED):
            event("prefix published an MSS invalidation")

        assert repr(sorted(item.items())) in later_exact, (
            f"{item['event_type']} at {item['event_at']} published on {split} candles was "
            f"revoked or rewritten once the series grew to {len(candles)}: {item['payload']}"
        )
