"""The no-repaint theorem at the replay level: structure and structure shift.

`test_no_repaint.py` and `test_no_repaint_zones.py` prove it where detection
starts -- a swing, a gap, a displacement is a fact about closed candles. Their
docstrings say the limit plainly: they run against the domain detectors, and a
replay that handed a detector the wrong window, or decided an event with a
number taken from the end of the window, would satisfy every one of them.

This file asks the replay services themselves. Each example runs the real
`StructureReplayService` and `StructureShiftReplayService`, through the golden
harness's in-memory ports, once on a prefix and once on the whole series, and
holds every event the prefix published to the events the whole series
publishes. An event may be *added* by later candles -- that is the market
moving on. An event the prefix published may not disappear, move, or change.

**Measured before it was written** (40 walking series, 320-380 candles):
BOS in 37, failed break in 29, CHOCH in 37, MSS in 30. `STRUCTURE_MSS_INVALIDATED`
occurred in none, so nothing here claims to cover it. Swing events: 3,811 kept
their strength and 25 were upgraded INTERNAL -> EXTERNAL, none moved or vanished.

**Series are at least 300 candles**, and so is every prefix. §1.9 gates every
detection replay at 300 closed candles; a shorter prefix publishes nothing and
would pass by having nothing to lose. That is also why examples are few: each
one is four replays.
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any

import pytest
from hypothesis import HealthCheck, event, given, settings
from hypothesis import strategies as st
from tests.golden.harness import runner
from tests.golden.harness.canonical import canonicalise
from tests.golden.harness.dataset import GoldenDataset
from tests.support.strategies import walking_candle_series

pytestmark = pytest.mark.property

_WARM = 300
_MAX_SERIES = 380

_REPLAY_SETTINGS = settings(
    max_examples=25,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.data_too_large],
)

# Facts a later candle may add about an earlier event. They are appended with
# the original's identity in their payload, never written over it, so their
# appearance in the full run alone is growth.
_SWING = "SWING_"


def _dataset(candles: list, engine: str) -> GoldenDataset:
    return GoldenDataset(
        dataset_id=f"property-{engine}",
        engine=engine,
        sls_sections=("3.1",),
        sls_rules=("property",),
        description="generated",
        labelling_rationale="generated by a property test",
        labelled_by="hypothesis",
        labelled_at="generated",
        algo_version="property",
        symbol=candles[0].symbol,
        timeframe=candles[0].timeframe,
        candles=tuple(candles),
        expected={},
        path=Path("generated.json"),
    )


def _events(engine: str, candles: list) -> list[dict[str, Any]]:
    run = runner._run_structure if engine == "structure" else runner._run_structure_shift

    return [canonicalise(item) for item in asyncio.run(run(_dataset(candles, engine)))["events"]]


def _key(item: dict[str, Any]) -> str:
    return json.dumps(item, sort_keys=True)


@_REPLAY_SETTINGS
@given(
    series=walking_candle_series(min_size=_WARM + 20, max_size=_MAX_SERIES),
    data=st.data(),
)
def test_a_replayed_structure_event_is_never_revoked_or_rewritten(
    series: list,
    data: st.DataObject,
) -> None:
    """§3.1, §3.3 and §3.5 at the replay: swings, labels, breaks, failed breaks.

    Swings get one allowance, and only in one direction. §3.1 stores a pivot
    once, "with strength = external" when it is both, and an internal swing
    confirms after two right candles while an external one needs five. So a
    prefix that ends two to four candles after a pivot publishes it as
    internal, and the whole series publishes the same pivot -- same index,
    same price, same time -- as external. That is the pivot being confirmed at
    a wider strength, not moved. A downgrade, a moved price or a vanished pivot
    is not allowed.

    Every other structure event the prefix published must be in the full run
    exactly as the prefix wrote it.
    """

    split = data.draw(st.integers(min_value=_WARM, max_value=len(series) - 1), label="prefix")

    early = _events("structure", series[:split])
    later = _events("structure", series)

    later_exact = {_key(item) for item in later}

    later_pivots: dict[tuple[str, str, int, str], set[str]] = {}

    for item in later:
        if item["event_type"].startswith(_SWING):
            _, strength, kind = item["event_type"].split("_")
            pivot = (kind, item["event_at"], item["payload"]["index"], item["payload"]["price"])
            later_pivots.setdefault(pivot, set()).add(strength)

    for item in early:
        if item["event_type"].startswith("BOS_"):
            event("prefix published a BOS")

        if item["event_type"].startswith(_SWING):
            _, strength, kind = item["event_type"].split("_")
            pivot = (kind, item["event_at"], item["payload"]["index"], item["payload"]["price"])
            strengths = later_pivots.get(pivot)

            assert strengths is not None, (
                f"{item['event_type']} at index {item['payload']['index']} published on "
                f"{split} candles is gone, or moved, once the series grew to {len(series)}"
            )

            if strength not in strengths:
                assert strength == "INTERNAL" and "EXTERNAL" in strengths, (
                    f"{item['event_type']} at index {item['payload']['index']} changed strength "
                    f"to {sorted(strengths)} when the series grew -- only INTERNAL -> EXTERNAL "
                    "is a confirmation rather than a rewrite"
                )
                event("a pivot was confirmed at external strength later")

            continue

        assert _key(item) in later_exact, (
            f"{item['event_type']} at {item['event_at']} published on {split} candles was "
            f"revoked or rewritten once the series grew to {len(series)}: {item['payload']}"
        )


@_REPLAY_SETTINGS
@given(
    series=walking_candle_series(min_size=_WARM + 20, max_size=_MAX_SERIES),
    data=st.data(),
)
def test_a_replayed_structure_shift_is_never_revoked_or_rewritten(
    series: list,
    data: st.DataObject,
) -> None:
    """§3.6 at the replay: CHoCH, MSS and the facts appended about an MSS.

    A CHoCH is a close through the protected swing, and an MSS confirms on
    follow-through inside five candles -- both are decided by candles that
    have already closed when they are published. So every shift event the
    prefix published must be in the full run exactly as written. The full run
    may publish more (an MSS whose follow-through arrived after the prefix
    ended, a low-quality mark on an earlier MSS); it may not publish less.
    """

    split = data.draw(st.integers(min_value=_WARM, max_value=len(series) - 1), label="prefix")

    early = _events("structure_shift", series[:split])
    later = {_key(item) for item in _events("structure_shift", series)}

    for item in early:
        if item["event_type"].startswith("MSS_"):
            event("prefix published an MSS")

        assert _key(item) in later, (
            f"{item['event_type']} at {item['event_at']} published on {split} candles was "
            f"revoked or rewritten once the series grew to {len(series)}: {item['payload']}"
        )
